# Generated by Django 4.1 on 2022-09-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewiew',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
