# Generated by Django 4.1 on 2022-09-02 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductApp', '0004_rewiew_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiew',
            new_name='Review',
        ),
    ]
