# Generated by Django 4.1 on 2022-09-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0005_rename_rewiew_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='to_user',
        ),
    ]
