# Generated by Django 4.1 on 2022-09-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0007_review_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
