# Generated by Django 4.1 on 2022-09-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0009_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
