# Generated by Django 4.1 on 2022-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0011_alter_review_product_alter_review_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
