# Generated by Django 4.1 on 2022-09-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0012_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_TL', models.CharField(default='TL', max_length=10)),
                ('currency_Dollar', models.CharField(default='$', max_length=10)),
                ('currency_Euro', models.CharField(default='€', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductApp.currency'),
        ),
    ]
