# Generated by Django 4.1.1 on 2022-09-20 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductApp', '0016_alter_category_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fav_user',
            field=models.ManyToManyField(related_name='fav_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
